Upload test results to wacklig

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -30,14 +30,20 @@ jobs:
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install pycodestyle
+          pip install pycodestyle unittest-xml-reporting
           pip install .
 
       - name: Test
-        run: python -m unittest -v
+        run: python -m xmlrunner discover -v -o test-results/test/
 
       - name: Pycodestyle
         run: pycodestyle cr8
+
+      - name: Upload results to wacklig
+        env:
+          WACKLIG_TOKEN: ${{ secrets.WACKLIG_TOKEN }}
+        run: |
+          curl -s https://raw.githubusercontent.com/pipifein/wacklig-uploader/master/wacklig.py | python - --token $WACKLIG_TOKEN || echo "Upload to wacklig failed"
 
   publish:
     name: Build & publish package to pypi
